cms_blog:
    resource: "@CmsBlogBundle/Resources/config/routing.yml"
    prefix:   /

cms_gallery:
    resource: "@CmsGalleryBundle/Resources/config/routing.yml"
    prefix:   /

cms_home_banner:
    resource: "@CmsHomeBannerBundle/Resources/config/routing.yml"
    prefix:   /

cms_xut:
    resource: "@CmsXutBundle/Resources/config/routing.yml"
    prefix:   /

