security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Cms\XutBundle\Entity\User:
                    algorithm:        sha512
                    encode_as_base64: false
                    iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
           administrators:
               entity: { class: CmsXutBundle:User }

    firewalls:
           main:
               pattern:    ^/
               form_login:
                  login_path: /locomotive/login
                  check_path: /locomotive/login_check
                  provider: administrators
               logout:
                  path:   /locomotive/logout
                  target: /
               anonymous: ~
    access_control:
      #     - { path: ^/locomotive, roles: ROLE_ADMIN }