parameters:
#    cms_blog.example.class: Cms\BlogBundle\Example

services:
#    cms_blog.example:
#        class: %cms_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
