parameters:
#    cms_gallery.example.class: Cms\GalleryBundle\Example

services:
#    cms_gallery.example:
#        class: %cms_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
