cms_xut_homepage:
    pattern:  /
    defaults: { _controller: CmsXutBundle:Default:index }
    requirements:
      _method:  GET

admin_area:
    pattern: /locomotive
    defaults: { _controller: CmsXutBundle:Admin:index }
    requirements:

login:
    pattern:   /locomotive/login
    defaults:  { _controller: CmsXutBundle:Security:login }

login_check:
    pattern:   /locomotive/login_check

logout:
    pattern:  /locomotive/logout

cms_categories_list:
    pattern: /locomotive/categories
    defaults: { _controller: CmsXutBundle:Category:edit }
    requirements:
        _method: GET

cms_category_new:
    pattern: /locomotive/categories/edit
    defaults: { _controller: CmsXutBundle:Category:new }

cms_category_create:
    pattern: /locomotive/categories/save/
    defaults: { _controller: CmsXutBundle:Category:save }
    requirements:
        _method: POST

cms_category_update:
    pattern: /locomotive/categories/save/{category_id}
    defaults: { _controller: CmsXutBundle:Category:save }
    requirements:
        _method: PUT
        category_id: \d+

cms_category_remove:
    pattern: /locomotive/categories/save/{category_id}
    defaults: { _controller: CmsXutBundle:Category:remove }
    requirements:
        _method: DELETE
        category_id: \d+