cms_xut_homepage:
    pattern:  /
    defaults: { _controller: CmsXutBundle:Default:index }
    requirements:
      _method:  GET

admin_area:
    pattern: /locomotive
    defaults: { _controller: CmsXutBundle:Admin:index }
    requirements:

login:
    pattern:   /locomotive/login
    defaults:  { _controller: CmsXutBundle:Security:login }

login_check:
    pattern:   /locomotive/login_check

logout:
    pattern:  /locomotive/logout

post_view:
    pattern: /blog/{post_id}
    defaults: { _controller: CmsXutBundle:Blog:view }
    requirements:
        _method: GET
        post_id: \d+

post_list:
    pattern: /blog/
    defaults: { _controller: CmsXutBundle:Blog:list }
    requirements:
        _method: GET

post_new:
    pattern: /editpost/
    defaults: { _controller: CmsXutBundle:Blog:edit }
    requirements:
        _method: GET

post_edit:
    pattern: /editpost/{post_id}
    defaults: { _controller: CmsXutBundle:Blog:edit }
    requirements:
        _method: GET

post_create:
    pattern: /savepost/
    defaults: { _controller: CmsXutBundle:Blog:save }
    requirements:
        _method: POST

post_update:
    pattern: /savepost/{post_id}
    defaults: { _controller: CmsXutBundle:Blog:save }
    requirements:
        _method: POST

post_remove:
    pattern: /removepost/{post_id}
    defaults: { _controller: CmsXutBundle:Blog:remove }
    requirements:
        _method: GET
        post_id: \d+