cms_xut_homepage:
    pattern:  /
    defaults: { _controller: CmsXutBundle:Default:index }
    requirements:
      _method:  GET

admin_area:
    pattern: /locomotive
    defaults: { _controller: CmsXutBundle:Admin:index }
    requirements:

login:
    pattern:   /locomotive/login
    defaults:  { _controller: CmsXutBundle:Security:login }

login_check:
    pattern:   /locomotive/login_check

logout:
    pattern:  /locomotive/logout

blog_index:
    pattern: /blog
    defaults: { _controller: CmsXutBundle:Blog:list }
    requirements:
        _method: GET

blog_list_posts:
    pattern: /blog
    defaults: { _controller: CmsXutBundle:Blog:list }
    requirements:
        _method: GET

blog_post_new:
    pattern: /blog/new
    defaults: { _controller: CmsXutBundle:Blog:edit }
    requirements:
        _method: GET

blog_post_edit:
    pattern: /blog/edit/{post_id}
    defaults: { _controller: CmsXutBundle:Blog:edit }
    requirements:
        _method: GET

blog_post_create:
    pattern: /blog/save
    defaults: { _controller: CmsXutBundle:Blog:save }
    requirements:
        _method: POST

blog_post_update:
    pattern: /blog/save/{post_id}
    defaults: { _controller: CmsXutBundle:Blog:save }
    requirements:
        _method: POST

blog_post_view:
    pattern: /blog/{post_id}
    defaults: { _controller: CmsXutBundle:Blog:view }
    requirements:
        _method: GET
        post_id: \d+

blog_post_remove:
    pattern: /blog/remove/{post_id}
    defaults: { _controller: CmsXutBundle:Blog:remove }
    requirements:
        _method: GET
        post_id: \d+

category_new:
    pattern: /editcat/
    defaults: { _controller: CmsXutBundle:Category:edit }
    requirements:
        _method: GET

category_edit:
    pattern: /editcat/{category_id}
    defaults: { _controller: CmsXutBundle:Category:edit }
    requirements:
        _method: GET

category_create:
    pattern: /savecat/
    defaults: { _controller: CmsXutBundle:Category:save }
    requirements:
        _method: POST

category_update:
    pattern: /savecat/{category_id}
    defaults: { _controller: CmsXutBundle:Category:save }
    requirements:
        _method: POST
        category_id: \d+