parameters:
    cms_gist_loader.class: Cms\XutBundle\GistLoader
    cms_config_cabinet.class: Cms\XutBundle\DependencyInjection\ConfigCabinet
    session_processor.class: Cms\XutBundle\DependencyInjection\Backpack

services:
    gist_loader:
        class: %cms_gist_loader.class%
    config:
        class: %cms_config_cabinet.class%
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
    backpack:
        class: %session_processor.class%
