parameters:
    cms_gist_loader.class: Cms\XutBundle\GistLoader
    cms_config_cabinet.class: Cms\XutBundle\ConfigCabinet

services:
    gist_loader:
        class: %cms_gist_loader.class%
    config_cabinet:
        class: %cms_config_cabinet.class%
